package modInter;


/**
* modInter/_IDLInterStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Friday, November 30, 2018 8:16:08 PM EST
*/

public class _IDLInterStub extends org.omg.CORBA.portable.ObjectImpl implements modInter.IDLInter
{

  public String receiveAndForwardRequest (String courseID, String semester, int capacity, String userID, String studentID, String oldCourseID, String newCourseID, int operationID, int sequenceID, String department, String error, String replicaNumber, boolean ack)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("receiveAndForwardRequest", true);
                $out.write_string (courseID);
                $out.write_string (semester);
                $out.write_long (capacity);
                $out.write_string (userID);
                $out.write_string (studentID);
                $out.write_string (oldCourseID);
                $out.write_string (newCourseID);
                $out.write_long (operationID);
                $out.write_long (sequenceID);
                $out.write_string (department);
                $out.write_string (error);
                $out.write_string (replicaNumber);
                $out.write_boolean (ack);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return receiveAndForwardRequest (courseID, semester, capacity, userID, studentID, oldCourseID, newCourseID, operationID, sequenceID, department, error, replicaNumber, ack        );
            } finally {
                _releaseReply ($in);
            }
  } // receiveAndForwardRequest

  public void startReceiving (String strReply, int port, String whichReplica)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startReceiving", true);
                $out.write_string (strReply);
                $out.write_long (port);
                $out.write_string (whichReplica);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                startReceiving (strReply, port, whichReplica        );
            } finally {
                _releaseReply ($in);
            }
  } // startReceiving

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:modInter/IDLInter:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IDLInterStub
