package modInter;


/**
* modInter/IDLInter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Friday, November 30, 2018 8:16:08 PM EST
*/

public interface IDLInter extends IDLInterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDLInter
