package modInter;


/**
* modInter/IDLInterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Friday, November 30, 2018 8:16:08 PM EST
*/

public interface IDLInterOperations 
{
  String receiveAndForwardRequest (String courseID, String semester, int capacity, String userID, String studentID, String oldCourseID, String newCourseID, int operationID, int sequenceID, String department, String error, String replicaNumber, boolean ack);
  void startReceiving (String strReply, int port, String whichReplica);
} // interface IDLInterOperations
